name: tee_zee_nator
description: Генератор технических заданий с использованием OpenAI API
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.18
  code_text_field: ^1.1.0
  # HTTP
  http: ^1.1.0
  dio: ^5.3.2
  # Локальное хранение
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Файлы
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  # JSON
  json_annotation: ^4.8.1
  # Утилиты
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - tz_pattern.md

flutter_launcher_icons:
  android: false # Отключаем Android, так как у нас desktop приложение
  ios: false # Отключаем iOS
  windows:
    generate: true
    image_path: "assets/icons/tee_zee_nator.ico"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icons/tee_zee_nator.icns"
