// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTemplate(arg1:string,arg2:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function GenerateRequirements(arg1:string,arg2:string):Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetDefaultTemplate():Promise<main.Template>;

export function GetModels():Promise<Array<main.Model>>;

export function GetTemplate(arg1:string):Promise<main.Template>;

export function GetTemplates():Promise<Array<main.Template>>;

export function Greet(arg1:string):Promise<string>;

export function IsConfigured():Promise<boolean>;

export function SaveConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestConnection():Promise<void>;

export function UpdateLastUsedModel(arg1:string):Promise<void>;

export function ValidateAndGetModels(arg1:string,arg2:string):Promise<Array<main.Model>>;
