// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTemplate(arg1, arg2) {
  return window['go']['main']['App']['AddTemplate'](arg1, arg2);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function GenerateRequirements(arg1, arg2) {
  return window['go']['main']['App']['GenerateRequirements'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDefaultTemplate() {
  return window['go']['main']['App']['GetDefaultTemplate']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetTemplate(arg1) {
  return window['go']['main']['App']['GetTemplate'](arg1);
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function SaveConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function UpdateLastUsedModel(arg1) {
  return window['go']['main']['App']['UpdateLastUsedModel'](arg1);
}

export function ValidateAndGetModels(arg1, arg2) {
  return window['go']['main']['App']['ValidateAndGetModels'](arg1, arg2);
}
